name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build extension
      run: pnpm build
      
    - name: Create Chrome Web Store package
      run: |
        cd frontend/extension/dist
        zip -r ../../../vetra-extension-${{ github.ref_name }}.zip .
        
    - name: Upload to Chrome Web Store
      uses: samuelmeuli/action-chrome-extension@v1
      with:
        extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        file-path: vetra-extension-${{ github.ref_name }}.zip
        publish: true
